version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10

  build:
    commands:
      - echo "Zipping lambda function..."
      - zip lambda_function.zip lambda_function.py

  post_build:
    commands:
      - echo "Uploading ZIP to S3..."
      - aws s3 cp lambda_function.zip s3://cicd-demo-lambda-code-bucket-123/lambda/lambda_function.zip


      - echo "Updating Lambda function..."
      aws lambda update-function-code --function-name cicd-demo-lambda --s3-bucket cicd-demo-lambda-code-bucket-123 --s3-key lambda/lambda_function.zip

